// Catalog of the most common Meshtastic-compatible hardware. hwModel
// numbers come from the meshtastic HardwareModel enum. Extracted from
// DeviceDatabasePanel so the antenna-overrides hook and other consumers
// can look up `stockAntennaDbi` without pulling in the whole panel.

export interface DeviceSpec {
  hwModel: number;
  name: string;
  vendor: string;
  chipFamily: 'ESP32' | 'ESP32-S3' | 'nRF52' | 'RP2040' | 'STM32' | 'Other';
  loraChip: 'SX1262' | 'SX1276' | 'SX1280' | 'LR1110' | 'Other';
  display: 'OLED-128x64' | 'OLED-128x32' | 'eink' | 'TFT' | 'none';
  battery: 'lipo' | 'aa' | 'usb-only' | 'integrated';
  gps: boolean;
  wifi: boolean;
  ble: boolean;
  maxTxDbm: number;
  stockAntennaDbi: number;
  approxPriceUsd: string;
  notes?: string;
  recommended?: string;
}

export const CATALOG: DeviceSpec[] = [
  // ── Classic ESP32 ──────────────────────────────────────────────────
  { hwModel: 1,  name: 'TLORA V2',            vendor: 'Lilygo',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 17, stockAntennaDbi: 2,   approxPriceUsd: '$20-30',  notes: 'Original TTGO LoRa board. Aging.' },
  { hwModel: 2,  name: 'TLORA V1',            vendor: 'Lilygo',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 17, stockAntennaDbi: 2,   approxPriceUsd: '$20-30',  notes: 'First-gen TTGO LoRa. Mostly obsolete.' },
  { hwModel: 3,  name: 'TLORA V2 1.6',        vendor: 'Lilygo',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 17, stockAntennaDbi: 2,   approxPriceUsd: '$20-30',  notes: 'Refreshed TTGO LoRa with USB-C.' },
  { hwModel: 4,  name: 'TBEAM',               vendor: 'Lilygo',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'lipo',   gps: true,  wifi: true,  ble: true, maxTxDbm: 20, stockAntennaDbi: 2,   approxPriceUsd: '$40-50',  notes: 'The classic GPS-equipped Meshtastic board.', recommended: 'Iconic tracker-class board.' },
  { hwModel: 5,  name: 'HELTEC V2 (1)',       vendor: 'Heltec',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 20, stockAntennaDbi: 2,   approxPriceUsd: '$20-30',  notes: 'Common starter board.' },
  { hwModel: 6,  name: 'TBEAM 0.7',           vendor: 'Lilygo',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'lipo',   gps: true,  wifi: true,  ble: true, maxTxDbm: 20, stockAntennaDbi: 2,   approxPriceUsd: '$40-50' },
  { hwModel: 8,  name: 'TLORA V1 1.3',        vendor: 'Lilygo',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 17, stockAntennaDbi: 2,   approxPriceUsd: '$20-25' },
  { hwModel: 9,  name: 'Heltec V1',           vendor: 'Heltec',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 17, stockAntennaDbi: 2,   approxPriceUsd: '$20' },
  { hwModel: 10, name: 'LILYGO LORA RELAY',   vendor: 'Lilygo',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'usb-only', gps: false, wifi: true, ble: true, maxTxDbm: 17, stockAntennaDbi: 2, approxPriceUsd: '$25' },
  { hwModel: 21, name: 'M5Stack ATOM',        vendor: 'M5Stack',   chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'none',        battery: 'integrated', gps: false, wifi: true, ble: true, maxTxDbm: 17, stockAntennaDbi: 2, approxPriceUsd: '$25-35', notes: 'Cube form factor with LoRa stack.' },
  { hwModel: 24, name: 'Heltec V2.1',         vendor: 'Heltec',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 20, stockAntennaDbi: 2,   approxPriceUsd: '$22-32' },
  { hwModel: 25, name: 'Heltec V2.1-1.6',     vendor: 'Heltec',    chipFamily: 'ESP32',    loraChip: 'SX1276', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 20, stockAntennaDbi: 2,   approxPriceUsd: '$22-32' },

  // ── nRF52 ──────────────────────────────────────────────────────────
  { hwModel: 7,  name: 'T-Echo',              vendor: 'Lilygo',    chipFamily: 'nRF52',    loraChip: 'SX1262', display: 'eink',        battery: 'lipo',   gps: true,  wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$70-80',  notes: 'Low-power nRF52 + e-ink. Weeks on a charge.', recommended: 'Best long-runtime tracker.' },
  { hwModel: 11, name: 'RAK4631',             vendor: 'RAKwireless', chipFamily: 'nRF52',  loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: true,  wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 3,   approxPriceUsd: '$80-110', notes: 'Modular: GPS, sensors, OLED come as separate slot-in modules.', recommended: 'Most popular nRF52 board. Excellent for solar/battery deployments.' },
  { hwModel: 51, name: 'NANO G2 ULTRA',       vendor: 'B&Q',       chipFamily: 'nRF52',    loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: true,  wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 3,   approxPriceUsd: '$90-110', notes: 'High-end nRF52 build with GPS in compact form factor.', recommended: 'Great pocket tracker.' },
  { hwModel: 63, name: 'NRF52 Pro Micro DIY', vendor: 'DIY',       chipFamily: 'nRF52',    loraChip: 'SX1262', display: 'none',        battery: 'lipo',   gps: false, wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$15-25',  notes: 'Bare nRF52 + LoRa module. Maker-grade.' },
  { hwModel: 69, name: 'Heltec Mesh Node T114', vendor: 'Heltec',  chipFamily: 'nRF52',    loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$30-40',  notes: 'Compact nRF52-based starter, very low idle current.' },
  { hwModel: 70, name: 'WIO Tracker WM1110',  vendor: 'Seeed',     chipFamily: 'nRF52',    loraChip: 'LR1110', display: 'none',        battery: 'integrated', gps: true, wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$50',     notes: 'LR1110 has built-in GNSS + WiFi-positioning.' },
  { hwModel: 72, name: 'RAK3172',             vendor: 'RAKwireless', chipFamily: 'STM32',  loraChip: 'SX1262', display: 'none',        battery: 'usb-only', gps: false, wifi: false, ble: false, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$20',     notes: 'STM32-based LoRa-only module.' },
  { hwModel: 88, name: 'XIAO nRF52 LoRa',     vendor: 'Seeed',     chipFamily: 'nRF52',    loraChip: 'SX1262', display: 'none',        battery: 'lipo',   gps: false, wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$15-25',  notes: 'Tiny postage-stamp form factor.' },
  { hwModel: 89, name: 'ThinkNode M1',        vendor: 'ThinkNode', chipFamily: 'nRF52',    loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: true,  wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 3,   approxPriceUsd: '$80-100' },
  { hwModel: 90, name: 'ThinkNode M2',        vendor: 'ThinkNode', chipFamily: 'nRF52',    loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: true,  wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 3,   approxPriceUsd: '$90-110' },

  // ── ESP32-S3 ───────────────────────────────────────────────────────
  { hwModel: 31, name: 'Station G1',          vendor: 'B&Q',       chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'none',        battery: 'integrated', gps: false, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 3, approxPriceUsd: '$50' },
  { hwModel: 39, name: 'Station G2',          vendor: 'B&Q',       chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'none',        battery: 'integrated', gps: false, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 3, approxPriceUsd: '$60-70', recommended: 'Solid headless router. Plug-in-and-go.' },
  { hwModel: 43, name: 'Heltec V3',           vendor: 'Heltec',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2.5, approxPriceUsd: '$25-35',  notes: 'Most popular Meshtastic starter today.', recommended: 'Recommended for first-time Meshtastic users.' },
  { hwModel: 44, name: 'Heltec WSL V3',       vendor: 'Heltec',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'none',        battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$15-20',  notes: 'Wireless-stick lite — no display. Cheap router.' },
  { hwModel: 48, name: 'Heltec Wireless Tracker', vendor: 'Heltec', chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'TFT', battery: 'lipo', gps: true, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 2.5, approxPriceUsd: '$45-60', notes: 'Heltec V3 with built-in GPS + bigger color screen.' },
  { hwModel: 49, name: 'Heltec Wireless Paper', vendor: 'Heltec',  chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'eink',        battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$25-35',  notes: 'E-ink display version — readable in sun.' },
  { hwModel: 50, name: 'T-Deck',              vendor: 'Lilygo',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'TFT',         battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$80-100', notes: 'Handheld with full QWERTY keyboard and color screen.', recommended: 'Best dedicated keyboard messenger.' },
  { hwModel: 52, name: 'PicoMputer S3',       vendor: 'community', chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'TFT',         battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$60-80',  notes: 'DIY handheld with thumb keyboard.' },
  { hwModel: 53, name: 'Heltec HT62',         vendor: 'Heltec',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'none',        battery: 'usb-only', gps: false, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$15-20' },
  { hwModel: 54, name: 'EByte ESP32-S3',      vendor: 'EByte',     chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$20-30' },
  { hwModel: 56, name: 'Chatter 2',           vendor: 'community', chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$30-40',  notes: 'Sleek handheld design.' },
  { hwModel: 66, name: 'Heltec Vision Master T190', vendor: 'Heltec', chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'TFT', battery: 'lipo', gps: true, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 2.5, approxPriceUsd: '$70-90', notes: '1.9" color display with GPS.' },
  { hwModel: 67, name: 'Heltec Vision Master E213', vendor: 'Heltec', chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'eink', battery: 'lipo', gps: true, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 2.5, approxPriceUsd: '$60-80', notes: '2.13" e-ink display with GPS.' },
  { hwModel: 68, name: 'Heltec Vision Master E290', vendor: 'Heltec', chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'eink', battery: 'lipo', gps: true, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 2.5, approxPriceUsd: '$80-100', notes: '2.9" e-ink display with GPS. Larger info display.' },
  { hwModel: 65, name: 'TBEAM Supreme',       vendor: 'Lilygo',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: true,  wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2.5, approxPriceUsd: '$55-65', notes: 'Modern T-Beam refresh on S3.' },
  { hwModel: 78, name: 'TLORA T3-S3',         vendor: 'Lilygo',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$25-35' },
  { hwModel: 81, name: 'XIAO ESP32-S3',       vendor: 'Seeed',     chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'none',        battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$15-20',  notes: 'Tiny S3 module + LoRa shield. Tiny footprint.' },
  { hwModel: 83, name: 'TLORA C6',            vendor: 'Lilygo',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$20-30',  notes: 'Newer C6 variant with WiFi 6.' },
  { hwModel: 92, name: 'Heltec Sensor Hub',   vendor: 'Heltec',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2,   approxPriceUsd: '$40-50',  notes: 'Heltec + environment-sensor breakouts.' },
  { hwModel: 94, name: 'Heltec Mesh Pocket',  vendor: 'Heltec',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'TFT',         battery: 'lipo',   gps: true,  wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2.5, approxPriceUsd: '$50-70', notes: 'Pocketable handheld with color display.', recommended: 'Decent all-rounder for backpacking.' },
  { hwModel: 95, name: 'Seeed Solar Node',    vendor: 'Seeed',     chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'none',        battery: 'integrated', gps: false, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 3, approxPriceUsd: '$70-90', notes: 'Built-in solar charging — set-and-forget remote router.', recommended: 'For permanent off-grid relay deployments.' },
  { hwModel: 97, name: 'TLORA Pager',         vendor: 'Lilygo',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'eink',        battery: 'lipo',   gps: true,  wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2.5, approxPriceUsd: '$60-80',  notes: 'Pager-style handheld with e-ink + keyboard.' },

  // ── 2.4 GHz LoRa (uncommon) ────────────────────────────────────────
  { hwModel: 45, name: 'BetaFPV 2.4G',        vendor: 'BetaFPV',   chipFamily: 'ESP32-S3', loraChip: 'SX1280', display: 'none',        battery: 'usb-only', gps: false, wifi: true, ble: true, maxTxDbm: 13, stockAntennaDbi: 2, approxPriceUsd: '$30', notes: '2.4 GHz LoRa — short range vs sub-GHz, but more global compatibility.' },
  { hwModel: 64, name: 'RadioMaster 900 Bandit Nano', vendor: 'RadioMaster', chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'none', battery: 'usb-only', gps: false, wifi: true, ble: true, maxTxDbm: 20, stockAntennaDbi: 2, approxPriceUsd: '$45', notes: 'Originally an RC transmitter module — reflashed for Meshtastic.' },
  { hwModel: 74, name: 'RadioMaster 900 Bandit', vendor: 'RadioMaster', chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'none', battery: 'usb-only', gps: false, wifi: true, ble: true, maxTxDbm: 27, stockAntennaDbi: 3, approxPriceUsd: '$60', notes: 'High-power RC transmitter variant.' },

  // ── RP2040 ─────────────────────────────────────────────────────────
  { hwModel: 46, name: 'RP2040 LoRa',         vendor: 'various',   chipFamily: 'RP2040',   loraChip: 'SX1262', display: 'OLED-128x64', battery: 'lipo',   gps: false, wifi: false, ble: false, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$15-25', notes: 'No wireless host comms — USB only.' },
  { hwModel: 47, name: 'Raspberry Pi Pico',   vendor: 'Raspberry Pi', chipFamily: 'RP2040', loraChip: 'SX1262', display: 'none',     battery: 'usb-only', gps: false, wifi: false, ble: false, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$10-15', notes: 'Pico + LoRa shield. Cheapest gateway.' },
  { hwModel: 76, name: 'RP2040 Feather RFM95', vendor: 'Adafruit', chipFamily: 'RP2040',   loraChip: 'SX1276', display: 'none',       battery: 'lipo',   gps: false, wifi: false, ble: false, maxTxDbm: 17, stockAntennaDbi: 2,   approxPriceUsd: '$30-40' },
  { hwModel: 79, name: 'Raspberry Pi Pico 2', vendor: 'Raspberry Pi', chipFamily: 'RP2040', loraChip: 'SX1262', display: 'none',     battery: 'usb-only', gps: false, wifi: false, ble: false, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$10-15', notes: 'Newer RP2350 variant.' },

  // ── Special / handheld ─────────────────────────────────────────────
  { hwModel: 71, name: 'Tracker T1000-E',     vendor: 'Seeed',     chipFamily: 'nRF52',    loraChip: 'LR1110', display: 'eink',        battery: 'integrated', gps: true, wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$110-130', notes: 'Compact tracker with e-ink + GNSS + sensors.', recommended: 'Top-tier tracker for hiking/SAR.' },
  { hwModel: 80, name: 'M5Stack CoreS3',      vendor: 'M5Stack',   chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'TFT',         battery: 'integrated', gps: false, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$50-70', notes: 'Cube handheld with color display + buttons.' },
  { hwModel: 91, name: 'T-ETH Elite',         vendor: 'Lilygo',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'none',        battery: 'usb-only', gps: false, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 3, approxPriceUsd: '$60-80', notes: 'Has wired Ethernet — useful as a fixed gateway.' },
  { hwModel: 96, name: 'Nomad Station G1',    vendor: 'community', chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'none',        battery: 'integrated', gps: false, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 3, approxPriceUsd: '$45-60' },
  { hwModel: 99, name: 'Wio WM1110',          vendor: 'Seeed',     chipFamily: 'nRF52',    loraChip: 'LR1110', display: 'none',        battery: 'integrated', gps: true, wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$30' },
  { hwModel: 100,name: 'RAK2560',             vendor: 'RAKwireless', chipFamily: 'nRF52',  loraChip: 'SX1262', display: 'none',        battery: 'integrated', gps: false, wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 3, approxPriceUsd: '$60-80', notes: 'Compact field router enclosure.' },
  { hwModel: 102, name:'Heltec Wireless Bridge', vendor: 'Heltec', chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'OLED-128x64', battery: 'usb-only', gps: false, wifi: true, ble: true, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$30-40', notes: 'Designed as WiFi/Eth ↔ LoRa bridge.' },
  { hwModel: 103, name:'Seeed Wio Tracker L1', vendor: 'Seeed',    chipFamily: 'nRF52',    loraChip: 'LR1110', display: 'none',        battery: 'integrated', gps: true, wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$80-100' },
  { hwModel: 104, name:'Seeed Wio Tracker L1 EInk', vendor: 'Seeed', chipFamily: 'nRF52', loraChip: 'LR1110', display: 'eink', battery: 'integrated', gps: true, wifi: false, ble: true, maxTxDbm: 22, stockAntennaDbi: 2, approxPriceUsd: '$100-120' },
  { hwModel: 106, name:'T-Deck Pro',          vendor: 'Lilygo',    chipFamily: 'ESP32-S3', loraChip: 'SX1262', display: 'TFT',         battery: 'lipo',   gps: true,  wifi: true,  ble: true, maxTxDbm: 22, stockAntennaDbi: 2.5, approxPriceUsd: '$100-130', notes: 'T-Deck with GPS + better battery + IMU.', recommended: 'Top-tier handheld for active field use.' },
];
